Update advpl_snippets.json
totvs/tds-vscode pull request #732
Opened 2021-07-01 14:53 UTC by HTM-Joaquim

Adição de funções novas e declarações de variáveis

2021-07-01 15:18 UTC, HTM-Joaquim commented on snippets/advpl_snippets.json
> +  // Funções
Remover comentário de arquivo .json

Em testes na base local a extensão .code-snippets não apresentou erro

2021-07-01 15:18 UTC, HTM-Joaquim commented on snippets/advpl_snippets.json
> +  // Declaração de variáveis
Remover comentário de arquivo .json

Em testes na base local a extensão .code-snippets não apresentou erro

2021-07-01 15:18 UTC, HTM-Joaquim commented on snippets/advpl_snippets.json
> +  // Operadores lógicos
Remover comentário de arquivo .json

Em testes na base local a extensão .code-snippets não apresentou erro

2021-07-01 17:34 UTC, lwtnb-wrk requested changes
favor substituir a identacao por TABS para manter o padrão corrente.
futuramente poderemos ate trocar o padrao de identacao para espacos, mas por enquanto favor seguir o padrao do fonte atual.
grato pela colaboracao

2021-07-05 11:42 UTC, lwtnb-wrk requested changes
@HTM-Joaquim O novo código enviado continua com espaços no lugar das TABS. Isso pode ser a configuração de sua IDE que pode trocar TABS por espaços ao salvar o arquivo.
Somente para contextualizar, o código original está com TABS então ao submeter essa alteração com espaços o Github não "entende" os espaços como se fossem os TABS e todo o fonte está sendo marcado como "diferente" mesmo que seja apenas essa troca de TABS por espaços. Com isso perdemos todo o histórico de alterações do arquivo. E por isso não podemos fazer o merge.

2021-07-05 11:57 UTC, HTM-Joaquim commented
@lwtnb-wrk estou tentando realizar o ajuste, mas não pareço estar conseguir ajustar a tabulação. Verifiquei nas configurações do VS Code, mas assim que subo o arquivo para o Git, ele altera.

2021-07-05 12:19 UTC, lwtnb-wrk approved these changes
@HTM-Joaquim O código agora aparece com TABS aqui e para mim está correto.
Existem pequenas alterações de formatação nos snippets originais, mas são coerentes e estou aceitando as correções de formatação.
Farei o merge com nossa branch Dev e testaremos os snippets agora. 
Grato pela Change Request.

2021-07-05 12:19 UTC, merged